from db_queries import *


#####################################
# begin completed global dataframes #
#####################################
# begin power
# begin alpha power
df_alphaAvgAllPower = get_data_alpha_avg_all()
df_alphaLengthPower = get_data_alpha_avg_length()
df_alphaCountPower = get_data_alpha_total_sold()
df_alphaBreakdownPower = get_data_alpha_breakdown()
df_alphaAllPower = get_data_alpha_all()
df_alphaCumulativeAllPower = get_data_alpha_cumulative_totals()
df_alphaStatsPower = get_data_alpha_power_stats()
df_alphaCumulativeAllPower = get_data_alpha_power_cumulative_totals()
# begin beta power
df_betaAvgAllPower = get_data_beta_avg_all()
df_betaLengthPower = get_data_beta_avg_length()
df_betaCountPower = get_data_beta_total_sold()
df_betaBreakdownPower = get_data_beta_breakdown()
df_betaAllPower = get_data_beta_all()
df_betaCumulativeAllPower = get_data_beta_cumulative_totals()
df_betaStatsPower = get_data_beta_power_stats()
df_betaCumulativeAllPower = get_data_beta_power_cumulative_totals()
# begin unlimited power
df_unlimitedAvgAllPower = get_data_unlimited_avg_all()
df_unlimitedLengthPower = get_data_unlimited_avg_length()
df_unlimitedCountPower = get_data_unlimited_total_sold()
df_unlimitedBreakdownPower = get_data_unlimited_breakdown()
df_unlimitedAllPower = get_data_unlimited_all()
df_unlimitedCumulativeAllPower = get_data_unlimited_cumulative_totals()
df_unlimitedStatsPower = get_data_unlimited_power_stats()
df_unlimitedCumulativeAllPower = get_data_unlimited_power_cumulative_totals()
# begin duals
# begin alpha duals
df_alphaAvgAllDuals = get_data_alpha_duals_avg_all()
df_alphaLengthDuals = get_data_alpha_duals_avg_length()
df_alphaCountDuals = get_data_alpha_duals_total_sold()
df_alphaBreakdownDuals = get_data_alpha_breakdown()
df_alphaAllDuals = get_data_alpha_duals_all()
df_alphaStatsDuals = get_data_alpha_duals_stats()
df_alphaCumulativeAllDuals = get_data_alpha_duals_cumulative_totals()
# begin beta duals
df_betaAvgAllDuals = get_data_beta_duals_avg_all()
df_betaLengthDuals = get_data_beta_duals_avg_length()
df_betaCountDuals = get_data_beta_duals_total_sold()
df_betaBreakdownDuals = get_data_beta_duals_breakdown()
df_betaAllDuals = get_data_beta_duals_all()
df_betaStatsDuals = get_data_beta_duals_stats()
df_betaCumulativeAllDuals = get_data_beta_duals_cumulative_totals()
# begin unlimited duals
df_unlimitedAvgAllDuals = get_data_unlimited_duals_avg_all()
df_unlimitedLengthDuals = get_data_unlimited_duals_avg_length()
df_unlimitedCountDuals = get_data_unlimited_duals_total_sold()
df_unlimitedBreakdownDuals = get_data_unlimited_duals_breakdown()
df_unlimitedAllDuals = get_data_unlimited_duals_all()
df_unlimitedStatsDuals = get_data_unlimited_duals_stats()
df_unlimitedCumulativeAllDuals = get_data_unlimited_duals_cumulative_totals()
# begin revised duals
df_revisedAvgAllDuals = get_data_revised_avg_all()
df_revisedLengthDuals = get_data_revised_avg_length()
df_revisedCountDuals = get_data_revised_total_sold()
df_revisedBreakdownDuals = get_data_revised_breakdown()
df_revisedAllDuals = get_data_revised_all()
df_revisedStatsDuals = get_data_revised_stats()
df_revisedCumulativeAllDuals = get_data_revised_cumulative_totals()

##################################
# begin active global dataframes #
##################################
# begin power
df_alphaActiveAllPower = get_data_alpha_active_all()
df_betaActiveAllPower = get_data_beta_active_all()
df_unlimitedActiveAllPower = get_data_unlimited_active_all()
# begin duals
df_alphaActiveAllDuals = get_data_alpha_duals_active_all()
df_betaActiveAllDuals = get_data_beta_duals_active_all()
df_unlimitedActiveAllDuals = get_data_unlimited_duals_active_all()
df_revisedActiveAllDuals = get_data_revised_active_all()

####################################
# begin completed global variables #
####################################
# begin power
# begin alpha power
alphaDataAvgPower = list(df_alphaAvgAllPower['completed_product_index_avg'])
alphaDataAvgTimestampPower = list(df_alphaAvgAllPower['timestamp'])
alphaDataLengthPower = list(df_alphaLengthPower['completed_product_index_length_avg'])
alphaDataLengthTimestampPower = list(df_alphaLengthPower['timestamp'])
alphaDataCountPower = list(df_alphaCountPower['completed_product_index_count_sum'])
alphaDataCountTimestampPower = list(df_alphaCountPower['timestamp'])
alphaDataBreakdownNamePower = list(df_alphaBreakdownPower['completed_product_nick'])
alphaDataBreakdownAvgPower = list(df_alphaBreakdownPower['completed_product_avg'])
alphaDataAllEndPower = list(df_alphaAllPower['completed_product_end'])
alphaDataAllNamePower = list(df_alphaAllPower['completed_product_nick'])
alphaDataAllHrefPower = list(df_alphaAllPower['completed_product_img_url'])
alphaDataAllPricePower = list(df_alphaAllPower['completed_product_prices'])
alphaDataCumulativePricePower = list(df_alphaCumulativeAllPower['completed_product_index_sum'])
alphaDataCumulativeTimestampPower = list(df_alphaCumulativeAllPower['timestamp'])
# begin beta power
betaDataAvgPower = list(df_betaAvgAllPower['completed_product_index_avg'])
betaDataAvgTimestampPower = list(df_betaAvgAllPower['timestamp'])
betaDataLengthPower = list(df_betaLengthPower['completed_product_index_length_avg'])
betaDataLengthTimestampPower = list(df_betaLengthPower['timestamp'])
betaDataCountPower = list(df_betaCountPower['completed_product_index_count_sum'])
betaDataCountTimestampPower = list(df_betaCountPower['timestamp'])
betaDataBreakdownNamePower = list(df_betaBreakdownPower['completed_product_nick'])
betaDataBreakdownAvgPower = list(df_betaBreakdownPower['completed_product_avg'])
betaDataAllEndPower = list(df_betaAllPower['completed_product_end'])
betaDataAllNamePower = list(df_betaAllPower['completed_product_nick'])
betaDataAllHrefPower = list(df_betaAllPower['completed_product_img_url'])
betaDataAllPricePower = list(df_betaAllPower['completed_product_prices'])
betaDataCumulativePricePower = list(df_betaCumulativeAllPower['completed_product_index_sum'])
betaDataCumulativeTimestampPower = list(df_betaCumulativeAllPower['timestamp'])
# begin unlimited power
unlimitedDataAvgPower = list(df_unlimitedAvgAllPower['completed_product_index_avg'])
unlimitedDataAvgTimestampPower = list(df_unlimitedAvgAllPower['timestamp'])
unlimitedDataLengthPower = list(df_unlimitedLengthPower['completed_product_index_length_avg'])
unlimitedDataLengthTimestampPower = list(df_unlimitedLengthPower['timestamp'])
unlimitedDataCountPower = list(df_unlimitedCountPower['completed_product_index_count_sum'])
unlimitedDataCountTimestampPower = list(df_unlimitedCountPower['timestamp'])
unlimitedDataBreakdownNamePower = list(df_unlimitedBreakdownPower['completed_product_nick'])
unlimitedDataBreakdownAvgPower = list(df_unlimitedBreakdownPower['completed_product_avg'])
unlimitedDataAllEndPower = list(df_unlimitedAllPower['completed_product_end'])
unlimitedDataAllNamePower = list(df_unlimitedAllPower['completed_product_nick'])
unlimitedDataAllHrefPower = list(df_unlimitedAllPower['completed_product_img_url'])
unlimitedDataAllPricePower = list(df_unlimitedAllPower['completed_product_prices'])
unlimitedDataCumulativePricePower = list(df_unlimitedCumulativeAllPower['completed_product_index_sum'])
unlimitedDataCumulativeTimestampPower = list(df_unlimitedCumulativeAllPower['timestamp'])
# begin duals
# begin unlimited duals
unlimitedDataAvgDuals = list(df_unlimitedAvgAllDuals['completed_product_index_avg'])
unlimitedDataAvgTimestampDuals = list(df_unlimitedAvgAllDuals['timestamp'])
unlimitedDataLengthDuals = list(df_unlimitedLengthDuals['completed_product_index_length_avg'])
unlimitedDataLengthTimestampDuals = list(df_unlimitedLengthDuals['timestamp'])
unlimitedDataCountDuals = list(df_unlimitedCountDuals['completed_product_index_count_sum'])
unlimitedDataCountTimestampDuals = list(df_unlimitedCountDuals['timestamp'])
unlimitedDataBreakdownNameDuals = list(df_unlimitedBreakdownDuals['completed_product_nick'])
unlimitedDataBreakdownAvgDuals = list(df_unlimitedBreakdownDuals['completed_product_avg'])
unlimitedDataAllEndDuals = list(df_unlimitedAllDuals['completed_product_end'])
unlimitedDataAllNameDuals = list(df_unlimitedAllDuals['completed_product_nick'])
unlimitedDataAllHrefDuals = list(df_unlimitedAllDuals['completed_product_img_url'])
unlimitedDataAllPriceDuals = list(df_unlimitedAllDuals['completed_product_prices'])
unlimitedDataCumulativePriceDuals = list(df_unlimitedCumulativeAllDuals['completed_product_index_sum'])
unlimitedDataCumulativeTimestampDuals = list(df_unlimitedCumulativeAllDuals['timestamp'])
# begin alpha duals
alphaDataAvgDuals = list(df_alphaAvgAllDuals['completed_product_index_avg'])
alphaDataAvgTimestampDuals = list(df_alphaAvgAllDuals['timestamp'])
alphaDataLengthDuals = list(df_alphaLengthDuals['completed_product_index_length_avg'])
alphaDataLengthTimestampDuals = list(df_alphaLengthDuals['timestamp'])
alphaDataCountDuals = list(df_alphaCountDuals['completed_product_index_count_sum'])
alphaDataCountTimestampDuals = list(df_alphaCountDuals['timestamp'])
alphaDataBreakdownNameDuals = list(df_alphaBreakdownDuals['completed_product_nick'])
alphaDataBreakdownAvgDuals = list(df_alphaBreakdownDuals['completed_product_avg'])
alphaDataAllEndDuals = list(df_alphaAllDuals['completed_product_end'])
alphaDataAllNameDuals = list(df_alphaAllDuals['completed_product_nick'])
alphaDataAllHrefDuals = list(df_alphaAllDuals['completed_product_img_url'])
alphaDataAllPriceDuals = list(df_alphaAllDuals['completed_product_prices'])
alphaDataCumulativePriceDuals = list(df_alphaCumulativeAllDuals['completed_product_index_sum'])
alphaDataCumulativeTimestampDuals = list(df_alphaCumulativeAllDuals['timestamp'])
# begin beta duals
betaDataAvgDuals = list(df_betaAvgAllDuals['completed_product_index_avg'])
betaDataAvgTimestampDuals = list(df_betaAvgAllDuals['timestamp'])
betaDataLengthDuals = list(df_betaLengthDuals['completed_product_index_length_avg'])
betaDataLengthTimestampDuals = list(df_betaLengthDuals['timestamp'])
betaDataCountDuals = list(df_betaCountDuals['completed_product_index_count_sum'])
betaDataCountTimestampDuals = list(df_betaCountDuals['timestamp'])
betaDataBreakdownNameDuals = list(df_betaBreakdownDuals['completed_product_nick'])
betaDataBreakdownAvgDuals = list(df_betaBreakdownDuals['completed_product_avg'])
betaDataAllEndDuals = list(df_betaAllDuals['completed_product_end'])
betaDataAllNameDuals = list(df_betaAllDuals['completed_product_nick'])
betaDataAllHrefDuals = list(df_betaAllDuals['completed_product_img_url'])
betaDataAllPriceDuals = list(df_betaAllDuals['completed_product_prices'])
betaDataCumulativePriceDuals = list(df_betaCumulativeAllDuals['completed_product_index_sum'])
betaDataCumulativeTimestampDuals = list(df_betaCumulativeAllDuals['timestamp'])
# begin unlimited duals
unlimitedDataAvgDuals = list(df_unlimitedAvgAllDuals['completed_product_index_avg'])
unlimitedDataAvgTimestampDuals = list(df_unlimitedAvgAllDuals['timestamp'])
unlimitedDataLengthDuals = list(df_unlimitedLengthDuals['completed_product_index_length_avg'])
unlimitedDataLengthTimestampDuals = list(df_unlimitedLengthDuals['timestamp'])
unlimitedDataCountDuals = list(df_unlimitedCountDuals['completed_product_index_count_sum'])
unlimitedDataCountTimestampDuals = list(df_unlimitedCountDuals['timestamp'])
unlimitedDataBreakdownNameDuals = list(df_unlimitedBreakdownDuals['completed_product_nick'])
unlimitedDataBreakdownAvgDuals = list(df_unlimitedBreakdownDuals['completed_product_avg'])
unlimitedDataAllEndDuals = list(df_unlimitedAllDuals['completed_product_end'])
unlimitedDataAllNameDuals = list(df_unlimitedAllDuals['completed_product_nick'])
unlimitedDataAllHrefDuals = list(df_unlimitedAllDuals['completed_product_img_url'])
unlimitedDataAllPriceDuals = list(df_unlimitedAllDuals['completed_product_prices'])
unlimitedDataCumulativePriceDuals = list(df_unlimitedCumulativeAllDuals['completed_product_index_sum'])
unlimitedDataCumulativeTimestampDuals = list(df_unlimitedCumulativeAllDuals['timestamp'])
# begin revised duals
revisedDataAvgDuals = list(df_revisedAvgAllDuals['completed_product_index_avg'])
revisedDataAvgTimestampDuals = list(df_revisedAvgAllDuals['timestamp'])
revisedDataLengthDuals = list(df_revisedLengthDuals['completed_product_index_length_avg'])
revisedDataLengthTimestampDuals = list(df_revisedLengthDuals['timestamp'])
revisedDataCountDuals = list(df_revisedCountDuals['completed_product_index_count_sum'])
revisedDataCountTimestampDuals = list(df_revisedCountDuals['timestamp'])
revisedDataBreakdownNameDuals = list(df_revisedBreakdownDuals['completed_product_nick'])
revisedDataBreakdownAvgDuals = list(df_revisedBreakdownDuals['completed_product_avg'])
revisedDataAllEndDuals = list(df_revisedAllDuals['completed_product_end'])
revisedDataAllNameDuals = list(df_revisedAllDuals['completed_product_nick'])
revisedDataAllHrefDuals = list(df_revisedAllDuals['completed_product_img_url'])
revisedDataAllPriceDuals = list(df_revisedAllDuals['completed_product_prices'])
revisedDataStatsNameDuals = list(df_revisedStatsDuals['completed_product_nick'])
revisedDataStatsAvgDuals = list(df_revisedStatsDuals['completed_product_avg'])
revisedDataStatsDepthDuals = list(df_revisedStatsDuals['completed_product_depth'])
revisedDataStatsLengthDuals = list(df_revisedStatsDuals['completed_product_avg_length'])
revisedDataStatsSumDuals = list(df_revisedStatsDuals['completed_product_sum'])
revisedDataCumulativePriceDuals = list(df_revisedCumulativeAllDuals['completed_product_index_sum'])
revisedDataCumulativeTimestampDuals = list(df_revisedCumulativeAllDuals['timestamp'])

#################################
# begin active global variables #
#################################
# begin power
# begin alpha power
alphaActiveDataAllStartPower = list(df_alphaActiveAllPower['active_product_start'])
alphaActiveDataAllNamePower = list(df_alphaActiveAllPower['active_product_nick'])
alphaActiveDataAllHrefPower = list(df_alphaActiveAllPower['active_product_img_url'])
alphaActiveDataAllPricePower = list(df_alphaActiveAllPower['active_product_prices'])
# begin beta power
betaActiveDataAllStartPower = list(df_betaActiveAllPower['active_product_start'])
betaActiveDataAllNamePower = list(df_betaActiveAllPower['active_product_nick'])
betaActiveDataAllHrefPower = list(df_betaActiveAllPower['active_product_img_url'])
betaActiveDataAllPricePower = list(df_betaActiveAllPower['active_product_prices'])
# begin unlimited power
unlimitedActiveDataAllStartPower = list(df_unlimitedActiveAllPower['active_product_start'])
unlimitedActiveDataAllNamePower = list(df_unlimitedActiveAllPower['active_product_nick'])
unlimitedActiveDataAllHrefPower = list(df_unlimitedActiveAllPower['active_product_img_url'])
unlimitedActiveDataAllPricePower = list(df_unlimitedActiveAllPower['active_product_prices'])

# begin duals
# begin alpha duals
alphaActiveDataAllStartDuals = list(df_alphaActiveAllDuals['active_product_start'])
alphaActiveDataAllNameDuals = list(df_alphaActiveAllDuals['active_product_nick'])
alphaActiveDataAllHrefDuals = list(df_alphaActiveAllDuals['active_product_img_url'])
alphaActiveDataAllPriceDuals = list(df_alphaActiveAllDuals['active_product_prices'])
# begin beta duals
betaActiveDataAllStartDuals = list(df_betaActiveAllDuals['active_product_start'])
betaActiveDataAllNameDuals = list(df_betaActiveAllDuals['active_product_nick'])
betaActiveDataAllHrefDuals = list(df_betaActiveAllDuals['active_product_img_url'])
betaActiveDataAllPriceDuals = list(df_betaActiveAllDuals['active_product_prices'])
# begin unlimited duals
unlimitedActiveDataAllStartDuals = list(df_unlimitedActiveAllDuals['active_product_start'])
unlimitedActiveDataAllNameDuals = list(df_unlimitedActiveAllDuals['active_product_nick'])
unlimitedActiveDataAllHrefDuals = list(df_unlimitedActiveAllDuals['active_product_img_url'])
unlimitedActiveDataAllPriceDuals = list(df_unlimitedActiveAllDuals['active_product_prices'])
# begin revised duals
revisedActiveDataAllStartDuals = list(df_revisedActiveAllDuals['active_product_start'])
revisedActiveDataAllNameDuals = list(df_revisedActiveAllDuals['active_product_nick'])
revisedActiveDataAllHrefDuals = list(df_revisedActiveAllDuals['active_product_img_url'])
revisedActiveDataAllPriceDuals = list(df_revisedActiveAllDuals['active_product_prices'])